<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="{{ url('dashboard/index') }}">控制面板</a>
        </li>
        <li>
            <a href="{{ url('menu/index') }}">导航管理</a>
        </li>
    </ul>
</div>
<div class="page-content">
<!--    <div class="col-lg-12">-->
<!--        <div class="alert alert-block alert-warning">-->
<!--            <button type="button" class="close" data-dismiss="alert">-->
<!--                <i class="icon-remove"></i>-->
<!--            </button>-->
<!---->
<!--        </div>-->

        <div class="btn-panel">
            {% if auth_list['admin/add'] is not empty %}
            <a href="{{ url('admin/add') }}" class="btn btn-success btn-sm" role="button">添加管理员</a>
            {% endif %}
            {% if auth_list['admin/refresh'] is not empty %}
            <a href="{{ url('menu/refresh') }}" class="btn btn-pink btn-sm" role="button">清除缓存</a>
            {% endif %}
        </div>


        <div class="widget-box transparent">
            <div class="widget-header widget-header-flat">
                <h4 class="lighter">
                    <i class="icon-star orange"></i>
                    <a href="{{ url('admin/index') }}">用户管理</a>
                    <small>
                        <i class="icon-double-angle-right"></i>
                        用户列表
                    </small>
                </h4>
                <div class="widget-toolbar">
                    <a href="#" data-action="collapse">
                        <i class="icon-chevron-up"></i>
                    </a>
                </div>
            </div>

            <div class="widget-body">
                <div class="widget-main no-padding">
                    <table class="table table-bordered table-striped table-hover tree-grid" id="menu-table">
                        <thead>
                        <tr>
                            <th>
                                <i class="icon-caret-right blue"></i>
                                id
                            </th>
                            <th>
                                <i class="icon-caret-right blue"></i>
                                名称
                            </th>
                            <th>
                                <i class="icon-caret-right blue"></i>
                                真实姓名
                            </th>
                            <th>
                                <i class="icon-caret-right blue"></i>
                                电话号码
                            </th>

                            <th>
                                <i class="icon-caret-right blue"></i>
                                详细描述
                            </th>

<!--                            <th>-->
<!--                                <i class="icon-caret-right blue"></i>-->
<!--                                创建者id-->
<!--                            </th>-->
                            <th>
                                <i class="icon-caret-right blue"></i>
                                创建时间
                            </th>
<!--                            <th>-->
<!--                                <i class="icon-caret-right blue"></i>-->
<!--                                修改者id-->
<!--                            </th>-->
                            </th>
                            <th>
                                <i class="icon-caret-right blue"></i>
                                修改时间
                            </th>

                            <th>
                                <i class="icon-caret-right blue"></i>
                                激活状态
                            </th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        {%if users is defined%}
                            <tbody>
                            {%for user in users%}

                                    <td>{{user.id}}</td>
                                    <td>{{user.username}}</td>
                                    <td>{{user.realname}}</td>
                                    <td>{{user.phone_number}}</td>
                                    <td>{{user.intro}}</td>
                                    <td>{{date('Y-m-d H:i:s',user.create_time)}}</td>
                                    <td>{{date('Y-m-d H:i:s',user.update_time)}}</td>

                                        {% if user.status==1 %}
                                        <td>激活</td>
                                        {% else %}
                                        <td>冻结</td>
                                        {% endif %}
                                    <td>
                                        {% if user.id==1 %}
                                        {% else %}
                                        {% if auth_list['admin/edit'] is not empty %}
                                        <a class="btn btn-xs btn-info" href="{{ url('admin/edit?id='~user['id']) }}">
                                            <i class="icon-edit bigger-120"></i>
                                        </a>
                                        {% endif%}

                                        {% if auth_list['admin/delete'] is not empty %}
                                        <button class="btn btn-xs btn-danger delete-menu" data-url="{{ url('admin/del?id='~user['id']) }}">
                                            <i class="icon-trash bigger-120"></i>
                                        </button>
                                        {% endif%}
                                        
                                        {% endif%}
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        {% else %}
                            <tbody>
                            <tr>
                                <td colspan="8">暂无数据</td>
                            </tr>
                            </tbody>
                        {% endif %}
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<link href="{{ static_url('bootstrap-editable/css/bootstrap-editable.css?_v=')~assetsVersion }}" rel="stylesheet"/>
<script src="{{ static_url('bootstrap-editable/js/bootstrap-editable.min.js?_v=')~assetsVersion }}"></script>
<script>
    $.fn.editable.defaults.mode = 'popup';
    $('.menu-sort-block').editable({
        params:function(params){
            params.sort = params.value;
            params.mid = params.pk;
            if(params.sort <= 0 || params.sort > 999){
                params.sort = 999;
            }
            return params;
        },
        success:function(response, value){
            if (typeof response !== 'object') response = JSON.parse(response);
            if(response.code == 1){
                tips_message(response.message, 'success');
            }else{
                tips_message(response.message, 'error');
            }
            return true;
        },
        error:function(response){
            tips_message('网络错误，请重试');
        },
        display:function(value){
            if(value <= 0 || value > 999){
                value = 999;
            }
            $(this).html(value);
        }
    });

    $('.delete-menu').on('click', function(){
        var dataUrl = $.trim($(this).attr('data-url'));
        if(!window.confirm('确定要删除选中菜单吗？此操作不可挽回')){
            return false;
        }
        window.location.href = dataUrl;
    });
</script>