<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="{{ url('dashboard/index') }}">控制面板</a>
        </li>
        <li>
            <a href="{{ url('menu/index') }}">导航管理</a>
        </li>
    </ul>
</div>
<div class="page-content">

        <div class="widget-box transparent">
            <div class="widget-header widget-header-flat">
                <h4 class="lighter">
                    <i class="icon-star orange"></i>
                    <a href="{{ url('admin/index') }}">日志管理</a>
                    <small>
                        <i class="icon-double-angle-right"></i>
                        日志列表
                    </small>
                </h4>
                <div class="widget-toolbar">
                    <a href="#" data-action="collapse">
                        <i class="icon-chevron-up"></i>
                    </a>
                </div>
            </div>

            <div class="widget-body">
                <div class="widget-main no-padding">
                    <table class="table table-bordered table-striped table-hover tree-grid" id="menu-table">
                        <thead>
                        <tr>
                            <th>
                                <i class="icon-caret-right blue"></i>
                                id
                            </th>
                            <th>
                                <i class="icon-caret-right blue"></i>
                                操作账户
                            </th>
                            <th>
                                <i class="icon-caret-right blue"></i>
                                操作url
                            </th>
<!--                            <th>-->
<!--                                <i class="icon-caret-right blue"></i>-->
<!--                                操作日志-->
<!--                            </th>-->

                            <th>
                                <i class="icon-caret-right blue"></i>
                                操作备注
                            </th>

                            <th>
                                <i class="icon-caret-right blue"></i>
                                操作时间
                            </th>

                            <th>
                                <i class="icon-caret-right blue"></i>
                                操作ip
                            </th>
                        </tr>
                        </thead>
                        {%if page.items is defined%}
                            <tbody>
                            {%for log in page.items%}
                                <tr>
                                    <td>{{log.id}}</td>
                                    <td>{{log.username}}</td>
                                    <td>{{log.url}}</td>
<!--                                    <td>{{log.query}}</td>-->
                                    <td>{{log.remark}}</td>
                                    <td>{{date('Y-m-d H:i:s',log.create_time)}}</td>
                                    <td>{{log.create_ip}}</td>

                                </tr>
                                {% endfor %}
                            </tbody>
                        {% else %}
                            <tbody>
                            <tr>
                                <td colspan="8">暂无数据</td>
                            </tr>
                            </tbody>
                        {% endif %}
                    </table>
                </div>
            </div>
        </div>

<div class="row">
    <div class="col-sm-2">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo "第".$page->current, "/", $page->total_pages."页" ?>
        </p>
    </div>
    <div class="col-sm-10 align-right">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("admin/log", "首页") ?></li>
                <li><?php echo $this->tag->linkTo("admin/log?page=" . $page->before, "上一页") ?></li>
                <li><?php echo $this->tag->linkTo("admin/log?page=" . $page->next, "下一页") ?></li>
                <li><?php echo $this->tag->linkTo("admin/log?page=" . $page->last, "最后一页") ?></li>
            </ul>
        </nav>
    </div>
</div>
</div>