<?php
namespace Marser\App\Models;

use Phalcon\Mvc\Model;
use \Marser\App\Models\BaseModel;
class Admin extends BaseModel
{
    public $id;
    public $username;
    public $password;
    public $realname;
    public $phone_number;
    public $intro;
    public $status;
    public $creater;
    public $create_time;
    public $create_ip;
    public $updater;
    public $update_time;
    public $role_id;
    public $email;
    public $salt;

    public function initialize()
    {
        $this->setSource("admin");
        parent::initialize();
    }
    public function getSource()
    {
        return 'admin';
    }
/*   public static function find($parameters = null)
   {
       parent::find($parameters); // TODO: Change the autogenerated stub
   }
   public static function findFirst($parameters = null)
   {
       parent::findFirst($parameters); // TODO: Change the autogenerated stub
   }
   public function save($data = null, $whiteList = null)
   {
       parent::save($data, $whiteList); // TODO: Change the autogenerated stub
   }*/
}