<div class="sidebar-shortcuts" id="sidebar-shortcuts">
</div>
<ul class="nav nav-list" id="sidebar-box">
        {% for menu in topList %}
        {% if menu is not empty %}
        <li>
        {% if menu['id'] is not empty %}
            <a href="javascript:void(0);" class="dropdown-toggle">
                <i class="icon-text-width"></i>
                <span class="menu-text"> {{ menu['name'] }} </span>
                <b class="arrow icon-angle-down"></b>
            </a>
        <ul class="submenu">
            {% if menu['id'] is not empty %}
            {% for second in topList['second'] %}


            {% if second['parent_id']==menu['id'] %}
            <li>
                <a href="{{ url(second['url']) }}">
                    <i class="icon-double-angle-right"></i>
                    {{ second['name'] }}
                </a>
            </li>

            {% endif %}
            {% endfor %}
            {% endif %}
        </ul>
        {% endif %}
        </li>
        {% endif %}
        {% endfor %}

<!--        <li>-->
<!--        <a href="javascript:void(0);" class="dropdown-toggle">-->
<!--            <i class="icon-cogs"></i>-->
<!--            <span class="menu-text"> 站点管理 </span>-->
<!--            <b class="arrow icon-angle-down"></b>-->
<!--        </a>-->
<!--        <ul class="submenu">-->
<!--            <li>-->
<!--                <a href="{{ url('menu/index') }}">-->
<!--                    <i class="icon-double-angle-right"></i>导航管理-->
<!--                </a>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="{{ url('menu/index') }}">-->
<!--                    <i class="icon-double-angle-right"></i>菜单管理-->
<!--                </a>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="{{ url('options/base') }}">-->
<!--                    <i class="icon-double-angle-right"></i>基本设置-->
<!--                </a>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="{{ url('options/read') }}">-->
<!--                    <i class="icon-double-angle-right"></i>阅读设置-->
<!--                </a>-->
<!--            </li>-->
        </ul>
<!--    </li>-->
<!--    <li>-->
<!--        <a href="javascript:void(0);" class="dropdown-toggle">-->
<!--            <i class="icon-cogs"></i>-->
<!--            <span class="menu-text"> 管理员管理 </span>-->
<!--            <b class="arrow icon-angle-down"></b>-->
<!--        </a>-->
<!--        <ul class="submenu">-->
<!--            <li>-->
<!--                <a href="{{ url('rights/write') }}">-->
<!--                    <i class="icon-double-angle-right"></i>角色管理-->
<!--                </a>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="{{ url('admin/base') }}">-->
<!--                    <i class="icon-double-angle-right"></i>用户管理-->
<!--                </a>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="{{ url('rights/index') }}">-->
<!--                    <i class="icon-double-angle-right"></i>权限资源-->
<!--                </a>-->
<!--            </li>-->
<!--        </ul>-->
<!--    </li>-->
</ul>
<div class="sidebar-collapse" id="sidebar-collapse">
    <i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
</div>
<script type="text/javascript">
    $('#sidebar-box a').each(function(){
        var href = $.trim($(this).attr('href'));
        if(href == window.location.pathname){
            $(this).parent("li").parent("ul").parent("li").addClass("active").addClass("open");
            $(this).parent("li").addClass("active");
            return false;
        }
    });
</script>